#PLAY LEVEL VARIABLES
- name: Variables from play level
  hosts: localhost
  vars_files:
  - variables.yaml
  vars:
    Person: "Punnam-Play"
    Wishes: "Good Morning- play" 
  tasks:
  - name: check variables   
    ansible.builtin.debug:
      msg: "Hi, {{Person}}, Good {{Wishes}} "

