- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print person
    ansible.builtin.package:
      name: "{{item}}" #item is default keyword
    loop:
    - git
    - mysql
    - postfix
